import Head from "next/head";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });
import HomePage from "../components/desktop/HomePage";
import About from "../components/desktop/About";
import Services from "../components/desktop/Services";
import Contacts from "../components/desktop/Contacts";
import DesktopSide from "../components/partials/DesktopSide";
import Media from "../components/partials/Media";
export default function Home() {
  return (
    <>
      <Head>
        <title>VARLSON</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Group-1.ico" />
      </Head>
      {/* DESKTOP RENDERING */}
      <main className="scroll-smooth hidde md:block  relative h-screen overflow-hidden bg-slate-400">
        <div className="hidden  bg-slate-800 md:grid place-self-center h-screen fixed w-48 p-3">
          <div className="border rounded-full justify-self-center h-24 w-24"></div>
          <div className=" text-white gap-4 place-self-center">
            <DesktopSide />
          </div>
          <div className="px-4 py-2 self-end justify-self-center pb-4">
            <Media />
          </div>
        </div>

        <div className="md:ml-48">
          <div id="home_page">
            <HomePage />
          </div>

          <div id="about">
            <About />
          </div>

          <div id="contact">
            <Contacts />
          </div>
          <div id="services">
            <Services />
          </div>
        </div>
      </main>
    </>
  );
}
